### PR TITLE
feat: Add transaction controller class

### LINKED ISSUE #13: set up transaction-controller with addTransaction

### PR DESCRIPTION
**Pull request by Silverguilt**
The code changes introduce a new `txController` class in the `tx-controller.mjs` file. This class handles the creation, retrieval, and deletion of transactions. It also includes methods to get all transactions and find a specific transaction by its ID. This addition enhances the functionality of the application by providing a centralized controller for managing transactions.

### CODE REVIEW

**Review by IgorRistic — APPROVED** [review]
Chuck Norris of programming—bugs run in fear when they see you coming 😀

**Review by G-jacobsson — COMMENTED** [review]
Maybe we shouldn't have deleteTx since it's supposed to be an immutable blockchain :)

**Review by G-jacobsson — APPROVED** [review]
Yippi kay yaay!

**Review by nathaliejanep — APPROVED** [review]
Goodie good!

**Pull request merged**
