### PR TITLE
Add methods updateChain and isValidChain

### LINKED ISSUE #27: Add validateChain in Blockchain model

### PR DESCRIPTION
**Pull request by nathaliejanep**
Instead of returning false I implemented Throw Error()
This should (hopefully) avoid crashing the server and throwing an error instead.

### CODE REVIEW

**Comment by IgorRistic** [comment]
Nicely structured!

 I wouldn't  know better.

**Review by IgorRistic — COMMENTED** [review]
⩥  Good job Nathalie ⩤

Nicely structured!
I wouldn't know better.

**Review by G-jacobsson — APPROVED** [review]
Looks perfect and easy to understand!

**Review by Silverguilt — APPROVED** [review]
Badabing badabong.

**Comment by Silverguilt** [comment]
On a more serious note, I'm glad you replaced the boolean with a Throw Error. Sick and tired of my server crashing all the time. Nice!

**Review by IgorRistic — APPROVED** [review]

**Pull request merged**
