### PR TITLE
Search bar and styling looks done. What you think?

### LINKED ISSUE #14: Create SearchBar and Styling

### PR DESCRIPTION
**Pull request by IgorRistic**

### CODE REVIEW

**Review by nathaliejanep — APPROVED** [review]

**Review by nathaliejanep — CHANGES_REQUESTED** [review]
Gooood! just add baseurl declaration

**Review by G-jacobsson — APPROVED** [review]
Looking good!!

**Review by G-jacobsson — APPROVED** [review]
Looks really nice :) Just need to add the component in App.jsx. And we need to pass the dynamicPort as a prop. 
I think you can delete the BASE_URL and add this in fetch: `http://localhost:${dynamicPort}/api/v1/obscoin/transactions/${txId}`

**Review by G-jacobsson — APPROVED** [review]
You can delete the whole const BASE_URL and add the url in the await fetch()

**Review by G-jacobsson — APPROVED** [review]
Nice! 😊 👌

**Review by nathaliejanep — APPROVED** [review]
Looking great

**Pull request merged**
